name: Version & Changelog Checker

on:
  pull_request:
    types: [opened, synchronize, reopened]
    branches:
      - main

jobs:
  check-version-and-changelog:
    name: Ensure Version & Changelog Updated
    runs-on: ubuntu-latest
    steps:
      - name: Checkout PR and base branch
        uses: actions/checkout@v4
        with:
          fetch-depth: 0  # Required for full diff comparison
          ref: ${{ github.head_ref }}

      - name: Fetch base branch for diff
        run: git fetch origin ${{ github.base_ref }}:refs/remotes/origin/${{ github.base_ref }}

      - name: Check plugin.yml version changed
        run: |
          echo "🔍 Checking plugin.yml version..."
          git diff origin/${{ github.base_ref }} -- plugin.yml | grep '^+version:' || {
            echo "❌ ERROR: 'version:' not updated in plugin.yml!"
            exit 1
          }

      - name: Check pom.xml version changed
        run: |
          echo "🔍 Checking pom.xml version..."
          git diff origin/${{ github.base_ref }} -- pom.xml | grep -E '^\+.*<version>.*</version>' || {
            echo "❌ ERROR: <version> not updated in pom.xml!"
            exit 1
          }

      - name: ✅ All checks passed
        run: echo "✅ plugin.yml and pom.xml version changes detected. All good!"
