name: Release on push to main

on:
  push:
    branches:
      - main

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Java
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Extract plugin.yml version
        id: plugin_version
        run: |
          PLUGIN_PATH=src/main/resources/plugin.yml
          version=$(grep '^version:' "$PLUGIN_PATH" | awk '{print $2}')
          echo "version=$version" >> $GITHUB_OUTPUT

      - name: Build with Maven
        run: mvn clean package -DskipTests

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: v${{ steps.plugin_version.outputs.version }}
          name: Release v${{ steps.plugin_version.outputs.version }}
          files: target/*.jar
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
