name: Publish to repo

on:
  push:
    branches: [ "main" ]

jobs:
  maven-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up JDK 21
      uses: actions/setup-java@v3
      with:
        distribution: 'temurin'
        java-version: '21'
        cache: 'maven'

    - name: Configure Maven settings
      run: |
        mkdir -p $HOME/.m2
        echo "<settings>
          <servers>
            <server>
              <id>lightmc-repository-releases</id>
              <username>${{ secrets.MAVEN_USERNAME }}</username>
              <password>${{ secrets.MAVEN_PASSWORD }}</password>
            </server>
          </servers>
        </settings>" > $HOME/.m2/settings.xml

    - name: Build and deploy with Maven
      run: mvn clean deploy --settings $HOME/.m2/settings.xml
